-- รัน SQL นี้ใน Supabase > SQL Editor
create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  date date not null,
  type text not null check (type in ('income','expense')),
  category text not null,
  detail text not null,
  amount numeric(12,2) not null check (amount > 0),
  created_at timestamptz not null default now()
);

alter table public.transactions enable row level security;

drop policy if exists "users can view own transactions" on public.transactions;
create policy "users can view own transactions" on public.transactions
for select using (auth.uid() = user_id);

drop policy if exists "users can insert own transactions" on public.transactions;
create policy "users can insert own transactions" on public.transactions
for insert with check (auth.uid() = user_id);

drop policy if exists "users can update own transactions" on public.transactions;
create policy "users can update own transactions" on public.transactions
for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "users can delete own transactions" on public.transactions;
create policy "users can delete own transactions" on public.transactions
for delete using (auth.uid() = user_id);

create index if not exists transactions_user_date_idx on public.transactions(user_id,date);
